archlinux:
  image: "archlinux:base-devel"
  before_script:
    - pacman -Sy cmake git --noconfirm --needed
  script:
    - git submodule init && git submodule update
    - mkdir build && cd build && cmake -DCOMPILE_TESTS:BOOL=ON ../ && make && ctest
